version: "3.8"

services:
  youtubejellyfinhardlink:
    build: .
    container_name: youtubejellyfinhardlink
    restart: no
    environment:
      SOURCE_DIR: ${SOURCE_DIR}
      DEST_DIR: ${DEST_DIR}
    dns:
      - 1.1.1.1
      - 1.0.0.1





