version: "3.8"

services:
  youtubejellyfinhardlink:
    build: .
    container_name: youtubejellyfinhardlink
    restart: "no"
    env_file:
      - .env
    volumes:
      - ${HOST_YOUTUBE}:/youtube
      - ${HOST_JELLYFIN}:/jellyfin